### ISSUE TITLE
Error with the NVIDIA links 

### ISSUE THREAD

**Issue by atg-abhishek** [ivylee/model-cards-and-datasheets#3]
@ivylee the NVIDIA links all lead to a 404 page - something wrong there?

**Comment by ivylee** [comment]
@atg-abhishek Updated the links in https://github.com/ivylee/model-cards-and-datasheets/commit/2e850535f7d5481806190dfe6114e7b991e072dc. Thanks!

**Comment by atg-abhishek** [comment]
Ah great! Thank you so much @ivylee :)
