### ISSUE TITLE
Expired Allen AI links

### ISSUE THREAD

**Issue by claudiur-deloitte** [ivylee/model-cards-and-datasheets#4]
Hi,
While scrolling through the list of model cards (great resources btw) I noticed that the following two links return error 404 Not Found. I haven't found a new address to where they might have been moved.

Links:
[PubMed Evidence Classifier, Allen AI](https://autocat.apps.allenai.org/?uid=35706625-67f6-45e5-933b-d40c4c753a17)
[Airline Complaints Classifier, Allen AI](https://autocat.apps.allenai.org/?uid=df78e70e-89a5-40d9-8951-36eff7642dac)

**Comment by ivylee** [comment]
Thanks for catching this! Indeed the entire Autocat project seems to have disappeared, unfortunately. Removed the dead links.

**Comment by atg-abhishek** [comment]
Hi Ivy,

Actually, a useful outcome of dead links might also be to track where and how model cards disappear over time to enhance transparency, which I see as one of the core contributions of the work you're doing with this repository. Thoughts?

Thanks!

Abhishek Gupta ( @atg_abhishek ( https://twitter.com/atg_abhishek ) )
Founder and Principal Researcher, Montreal AI Ethics Institute ( https://montrealethics.ai/ )
Director, Responsible AI, Boston Consulting Group (BCG) ( https://www.bcg.com/about/people/experts/abhishek-gupta )
Fellow, Augmented Collective Intelligence, BCG Henderson Institute ( https://bcghendersoninstitute.com/contributors/abhishek-gupta/ )
Author, State of AI Ethics Report ( https://montrealethics.ai/state ) and AI Ethics Brief ( https://brief.montrealethics.ai/ )
Chair, Standards Working Group, Green Software Foundation ( https://greensoftware.foundation/ )
Learn more about my work here ( https://atg-abhishek.github.io/ ). You can now support my work by buying me a coffee ( https://buymeacoff.ee/abhishekgupta ) !

**Comment by ivylee** [comment]
@atg-abhishek Precisely, removals are tracked in Git commits, e.g. [3a7591b](https://github.com/ivylee/model-cards-and-datasheets/commit/3a7591beab679525451ba8d1db4afb4a497f9b0b).

**Comment by atg-abhishek** [comment]
Awesome, thank you for your efforts in maintaining this repo!!

Abhishek Gupta ( @atg_abhishek ( https://twitter.com/atg_abhishek ) )
Founder and Principal Researcher, Montreal AI Ethics Institute ( https://montrealethics.ai/ )
Director, Responsible AI, Boston Consulting Group (BCG) ( https://www.bcg.com/about/people/experts/abhishek-gupta )
Fellow, Augmented Collective Intelligence, BCG Henderson Institute ( https://bcghendersoninstitute.com/contributors/abhishek-gupta/ )
Author, State of AI Ethics Report ( https://montrealethics.ai/state ) and AI Ethics Brief ( https://brief.montrealethics.ai/ )
Chair, Standards Working Group, Green Software Foundation ( https://greensoftware.foundation/ )
Learn more about my work here ( https://atg-abhishek.github.io/ ). You can now support my work by buying me a coffee ( https://buymeacoff.ee/abhishekgupta ) !
